### ISSUE TITLE
Display previous guesses and hints

### ISSUE THREAD

**Issue by JEmersonLawrance** [JacobAKnox/CST316JuniorProject#2]
As a player, I want to see my previous guesses and hints, so that I get more information toward the correct answer

Acceptance:
For each incorrect guess, display the guesses country/territory and the cardinal direction to the correct guess

**Comment by JEmersonLawrance** [comment]
Need to find way to update previous guesses and hints by pulling the data from the game and displaying them in the InfoPanel component. Once that is figured out and implemented, this user story is complete.

**Comment by JEmersonLawrance** [comment]
^ actually not complete yet. Now that I have this implemented, I have to calculate the direction based on lat/long of guess compared to the goal country and display that on infopanel next to guess.

**Comment by JacobAKnox** [comment]
I think this is done, will you close the issue and move to done if so?

**Comment by JEmersonLawrance** [comment]
👍
