### ISSUE TITLE
Pick a new puzzle each day

### ISSUE THREAD

**Issue by RayyanOIT** [JacobAKnox/CST316JuniorProject#5]
As a player, I want a new puzzle each of my calendar days, so that I have regular new puzzles

Acceptance:
All players playing that day see the global puzzle for that day,
the global puzzle is a combination of a US city and other country/territory that has a city of the same name
A new puzzle should be chosen at midnight local to the player

**Comment by JacobAKnox** [comment]
Todo:
Grab puzzle from database
add time feature

**Comment by JacobAKnox** [comment]
Puzzles now get picked randomly
